package com.folha.boot.Reposytory;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.folha.boot.domain.AnoMes;
import com.folha.boot.domain.AtividadeEscala;
import com.folha.boot.domain.HorasFaltasFolhasVariaveis;
import com.folha.boot.domain.Unidades;

@Repository
public interface HorasFaltasFolhasVariaveisReposytory extends JpaRepository<HorasFaltasFolhasVariaveis, Long>{

	public List<HorasFaltasFolhasVariaveis> findByHorasRestantesGreaterThanAndIdAnoMesFkIdEscalaBloqueadaFkSiglaAndDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc( Integer numero, String sigla);
	
	public List<HorasFaltasFolhasVariaveis> findByDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc();
	
	public List<HorasFaltasFolhasVariaveis> findByIdAnoMesFkAndDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc(AnoMes anoMes);

	
	public List<HorasFaltasFolhasVariaveis> findByIdUnidadeFkAndDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc(Unidades unidades);
		
	public List<HorasFaltasFolhasVariaveis> findByIdUnidadeFkAndIdFuncionarioFkIdPessoaFkNomeContainingAndDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc(Unidades unidades, String nome);
	
	
	public Page<HorasFaltasFolhasVariaveis> findByIdUnidadeFkAndDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc(Unidades unidades, final Pageable page);
	
	public Page<HorasFaltasFolhasVariaveis> findByIdUnidadeFkAndIdFuncionarioFkIdPessoaFkNomeContainingAndDtCancelamentoIsNullOrderByIdAnoMesFkNomeAnoMesDescIdFuncionarioFkIdPessoaFkNomeAsc(Unidades unidades, String nome, final Pageable page);
	
}
