package com.folha.boot.Reposytory;


import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import com.folha.boot.domain.CodigoDiferenciado;
import com.folha.boot.domain.IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado;

@Repository
public interface IncompatibilidadeCodigoDiferenciadoCodigoDiferenciadoReposytory extends JpaRepository<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado, Long> {
	
	public List<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado> findAllByOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoIncompativelFkNomeCodigoDiferenciadoAsc( );
	
	public List<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkNomeCodigoDiferenciadoContainingOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoIncompativelFkNomeCodigoDiferenciadoAsc(String nome);
	
	public List<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoIncompativelFkNomeCodigoDiferenciadoAsc(CodigoDiferenciado codigoDiferenciado);
	
	public List<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkAndIdCodigoDiferenciadoIncompativelFkOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoIncompativelFkNomeCodigoDiferenciadoAsc(CodigoDiferenciado codigoDiferenciado, CodigoDiferenciado codigoDiferenciadoIncompativel);
	
	
	public Page<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado> findAllByOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoIncompativelFkNomeCodigoDiferenciadoAsc( final Pageable pageable);
	
	public Page<IncompatibilidadeCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkNomeCodigoDiferenciadoContainingOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoIncompativelFkNomeCodigoDiferenciadoAsc(String nome, final Pageable pageable);
	
	
}
