package com.folha.boot.Reposytory;


import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.folha.boot.domain.CodigoDiferenciado;
import com.folha.boot.domain.PreRequisitoCodigoDiferenciadoCodigoDiferenciado;

@Repository
public interface PreRequisitoCodigoDiferenciadoCodigoDiferenciadoReposytory extends JpaRepository<PreRequisitoCodigoDiferenciadoCodigoDiferenciado, Long> {
	
	public List<PreRequisitoCodigoDiferenciadoCodigoDiferenciado> findAllByOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoCompativelFkNomeCodigoDiferenciadoAsc( );
	
	public List<PreRequisitoCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkNomeCodigoDiferenciadoContainingOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoCompativelFkNomeCodigoDiferenciadoAsc(String nome);
	
	public List<PreRequisitoCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoCompativelFkNomeCodigoDiferenciadoAsc(CodigoDiferenciado codigoDiferenciado);
	
	public List<PreRequisitoCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkAndIdCodigoDiferenciadoCompativelFkOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoCompativelFkNomeCodigoDiferenciadoAsc(CodigoDiferenciado codigoDiferenciado, CodigoDiferenciado codigoDiferenciadoCompativel);
	
	
	public Page<PreRequisitoCodigoDiferenciadoCodigoDiferenciado> findAllByOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoCompativelFkNomeCodigoDiferenciadoAsc( final Pageable pageable);
	
	public Page<PreRequisitoCodigoDiferenciadoCodigoDiferenciado> findByIdCodigoDiferenciadoFkNomeCodigoDiferenciadoContainingOrderByIdCodigoDiferenciadoFkIdUnidadeFkNomeFantasiaAscIdCodigoDiferenciadoFkNomeCodigoDiferenciadoAscIdCodigoDiferenciadoCompativelFkNomeCodigoDiferenciadoAsc(String nome, final Pageable pageable);
	
	
}
